In [4]:
import numpy as np
import pandas as pd

In [5]:
!wget https://raw.githubusercontent.com/EmKa-Academy/Canli-Ders-Notebooklari/refs/heads/main/Batch-1/Pandas-Dersleri/DATA/tips.csv

--2025-03-29 08:49:21--  https://raw.githubusercontent.com/EmKa-Academy/Canli-Ders-Notebooklari/refs/heads/main/Batch-1/Pandas-Dersleri/DATA/tips.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18505 (18K) [text/plain]
Saving to: ‘tips.csv.1’

tips.csv.1          100%[===================>]  18.07K  --.-KB/s    in 0.002s

2025-03-29 08:49:21 (10.0 MB/s) - ‘tips.csv.1’ saved [18505/18505]

In [6]:
df = pd.read_csv('/content/tips.csv')
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [7]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

# Built-in funksiyalar və metodlar

# .apply()

# I yol

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [9]:
def son4(number):
    return str(number)[-4:]

In [10]:
df['CC Number'].apply(son4)

0      3410
1      9230
2      1322
3      5994
4      7221
       ...
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: object

In [11]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [12]:
df['CC Number'] = df['CC Number'].apply(son4)

In [13]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

# II yol

In [14]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    object
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(1), object(7)
memory usage: 21.1+ KB

In [16]:
df['CC Number'] = df['CC Number'].apply(lambda x: str(x)[-4:])

In [17]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

# III yol

In [18]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [19]:
df['CC Number'].astype(str).str[-4:]

0      3410
1      9230
2      1322
3      5994
4      7221
       ...
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: object

In [20]:
df['CC Number'] = df['CC Number'].astype(str).str[-4:]

In [21]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [22]:
# Əgər ödənən hesab 10 -dan azdırsa $ simvolu, 10 və 30 arasındadırsa $$, 30 dan çoxdursa $$$ simvolu yeni sütunda uyğun olaraq yazılsın

# I yol

In [23]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [24]:
def fiyat_kateqori(x):
    if x < 10 :
        return '$'
    elif 10 <= x < 30 :
        return '$$'
    else :
        return '$$$'

In [25]:
df['total_bill'].apply(fiyat_kateqori)

0      $$
1      $$
2      $$
3      $$
4      $$
       ..
239    $$
240    $$
241    $$
242    $$
243    $$
Name: total_bill, Length: 244, dtype: object

In [26]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [27]:
df['price_category'] = df['total_bill'].apply(fiyat_kateqori)

In [28]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

# II yol lambda expression

In [29]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [30]:
df['price_category'] = df['total_bill'].apply(lambda x : '$' if x < 10 else '$$' if 10 <= x < 30 else '$$$')

In [31]:
df.sample(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
36,16.31,2.00,Male,No,Sat,Dinner,3,5.44,William Ford,9398,Sat9139,$$
225,16.27,2.50,Female,Yes,Fri,Lunch,2,8.14,Whitney Arnold,7428,Fri6665,$$
123,15.95,2.00,Male,No,Thur,Lunch,2,7.98,Christopher Lang,8319,Thur1992,$$
43,9.68,1.32,Male,No,Sun,Dinner,2,4.84,Christopher Spears,9212,Sun3279,$
167,31.71,4.50,Male,No,Sun,Dinner,4,7.93,Michael Lawson,7119,Sun3719,$$$
160,21.50,3.50,Male,No,Sun,Dinner,4,5.38,Travis Gonzalez,4685,Sun245,$$
220,12.16,2.20,Male,Yes,Fri,Lunch,2,6.08,Ricky Johnson,0736,Fri4607,$$
131,20.27,2.83,Female,No,Thur,Lunch,2,10.14,Ashley Burke,0066,Thur9005,$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,2842,Sat2657,$$

# III yol vectorized (ən sürətlisi)

In [32]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [33]:
df.drop('price_category', axis = 1, inplace=True )

In [34]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [35]:
np.full((2,3), 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [36]:
def fiyat_kateqori_vectorized(bill):
    categories = np.full_like(bill, '$', dtype= 'U3')
    categories[(bill >= 10) & (bill < 30)] = '$$'
    categories[bill >= 30] = '$$$'
    return categories

In [37]:
df['total_bill'].keys()

RangeIndex(start=0, stop=244, step=1)

In [38]:
df['total_bill'].values

array([16.99, 10.34, 21.01, 23.68, 24.59, 25.29,  8.77, 26.88, 15.04,
       14.78, 10.27, 35.26, 15.42, 18.43, 14.83, 21.58, 10.33, 16.29,
       16.97, 20.65, 17.92, 20.29, 15.77, 39.42, 19.82, 17.81, 13.37,
       12.69, 21.7 , 19.65,  9.55, 18.35, 15.06, 20.69, 17.78, 24.06,
       16.31, 16.93, 18.69, 31.27, 16.04, 17.46, 13.94,  9.68, 30.4 ,
       18.29, 22.23, 32.4 , 28.55, 18.04, 12.54, 10.29, 34.81,  9.94,
       25.56, 19.49, 38.01, 26.41, 11.24, 48.27, 20.29, 13.81, 11.02,
       18.29, 17.59, 20.08, 16.45,  3.07, 20.23, 15.01, 12.02, 17.07,
       26.86, 25.28, 14.73, 10.51, 17.92, 27.2 , 22.76, 17.29, 19.44,
       16.66, 10.07, 32.68, 15.98, 34.83, 13.03, 18.28, 24.71, 21.16,
       28.97, 22.49,  5.75, 16.32, 22.75, 40.17, 27.28, 12.03, 21.01,
       12.46, 11.35, 15.38, 44.3 , 22.42, 20.92, 15.36, 20.49, 25.21,
       18.24, 14.31, 14.  ,  7.25, 38.07, 23.95, 25.71, 17.31, 29.93,
       10.65, 12.43, 24.08, 11.69, 13.42, 14.26, 15.95, 12.48, 29.8 ,
        8.52, 14.52, 11.38, 22.82, 19.08, 20.27, 11.17, 12.26, 18.26,
        8.51, 10.33, 14.15, 16.  , 13.16, 17.47, 34.3 , 41.19, 27.05,
       16.43,  8.35, 18.64, 11.87,  9.78,  7.51, 14.07, 13.13, 17.26,
       24.55, 19.77, 29.85, 48.17, 25.  , 13.39, 16.49, 21.5 , 12.66,
       16.21, 13.81, 17.51, 24.52, 20.76, 31.71, 10.59, 10.63, 50.81,
       15.81,  7.25, 31.85, 16.82, 32.9 , 17.89, 14.48,  9.6 , 34.63,
       34.65, 23.33, 45.35, 23.17, 40.55, 20.69, 20.9 , 30.46, 18.15,
       23.1 , 15.69, 19.81, 28.44, 15.48, 16.58,  7.56, 10.34, 43.11,
       13.  , 13.51, 18.71, 12.74, 13.  , 16.4 , 20.53, 16.47, 26.59,
       38.73, 24.27, 12.76, 30.06, 25.89, 48.33, 13.27, 28.17, 12.9 ,
       28.15, 11.59,  7.74, 30.14, 12.16, 13.42,  8.58, 15.98, 13.42,
       16.27, 10.09, 20.45, 13.28, 22.12, 24.01, 15.69, 11.61, 10.77,
       15.53, 10.07, 12.6 , 32.83, 35.83, 29.03, 27.18, 22.67, 17.82,
       18.78])

In [39]:
df['price_category'] = fiyat_kateqori_vectorized(df['total_bill'].values)

In [40]:
df.sample(7)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
136,10.33,2.00,Female,No,Thur,Lunch,2,5.16,Donna Kelly,6376,Thur1393,$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,9786,Sun3775,$$
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,6453,Thur3621,$$$
159,16.49,2.00,Male,No,Sun,Dinner,4,4.12,Christopher Soto,1434,Sun1781,$$
40,16.04,2.24,Male,No,Sat,Dinner,3,5.35,Adam Edwards,9420,Sat8549,$$
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,1962,Sat3374,$$

# .apply() metodunu birdən çox sütuna tətbiq etmək

# I yol

In [41]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [42]:
def square(x):
    return x**2

In [43]:
# df[['total_bill', 'tip']] = df[['total_bill', 'tip']].apply(square)
df[['total_bill', 'tip']].apply(square)

     total_bill      tip
0      288.6601   1.0201
1      106.9156   2.7556
2      441.4201  12.2500
3      560.7424  10.9561
4      604.6681  13.0321
..          ...      ...
239    842.7409  35.0464
240    738.7524   4.0000
241    513.9289   4.0000
242    317.5524   3.0625
243    352.6884   9.0000

[244 rows x 2 columns]

# II yol

In [44]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [45]:
df[['total_bill', 'tip']].apply(lambda x : x**2 )
# df[['total_bill', 'tip']] = df[['total_bill', 'tip']].apply(lambda x: x**2)

     total_bill      tip
0      288.6601   1.0201
1      106.9156   2.7556
2      441.4201  12.2500
3      560.7424  10.9561
4      604.6681  13.0321
..          ...      ...
239    842.7409  35.0464
240    738.7524   4.0000
241    513.9289   4.0000
242    317.5524   3.0625
243    352.6884   9.0000

[244 rows x 2 columns]

# III yol vectorized(ən sürətlisi)

In [46]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [47]:
# df['total_bill'] = np.square(df['total_bill'])
np.square(df['total_bill'])

0      288.6601
1      106.9156
2      441.4201
3      560.7424
4      604.6681
         ...
239    842.7409
240    738.7524
241    513.9289
242    317.5524
243    352.6884
Name: total_bill, Length: 244, dtype: float64

In [48]:
# df[['total_bill', 'tip']] = np.square(df[['total_bill', 'tip']])
np.square(df[['total_bill', 'tip']])

     total_bill      tip
0      288.6601   1.0201
1      106.9156   2.7556
2      441.4201  12.2500
3      560.7424  10.9561
4      604.6681  13.0321
..          ...      ...
239    842.7409  35.0464
240    738.7524   4.0000
241    513.9289   4.0000
242    317.5524   3.0625
243    352.6884   9.0000

[244 rows x 2 columns]

In [49]:
df.describe()

       total_bill         tip        size  price_per_person
count  244.000000  244.000000  244.000000        244.000000
mean    19.785943    2.998279    2.569672          7.888197
std      8.902412    1.383638    0.951100          2.914234
min      3.070000    1.000000    1.000000          2.880000
25%     13.347500    2.000000    2.000000          5.800000
50%     17.795000    2.900000    2.000000          7.255000
75%     24.127500    3.562500    3.000000          9.390000
max     50.810000   10.000000    6.000000         20.270000

In [50]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [51]:
df.sort_values(by = 'total_bill', ascending= True) #default halda ascending True olduğu üçün artan sıra ilə sıralayır

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,5267,Sat3455,$
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,6392,Fri3780,$
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,6887,Sat4801,$
172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,Larry White,3103,Sun9209,$
149,7.51,2.00,Male,No,Thur,Lunch,2,3.76,Daniel Robbins,1889,Thur6321,$
...,...,...,...,...,...,...,...,...,...,...,...,...
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$

In [52]:
df.sort_values(by = 'total_bill', ascending= False) # azalan sira ile

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$
...,...,...,...,...,...,...,...,...,...,...,...,...
149,7.51,2.00,Male,No,Thur,Lunch,2,3.76,Daniel Robbins,1889,Thur6321,$
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,6887,Sat4801,$
172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,Larry White,3103,Sun9209,$
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,6392,Fri3780,$
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,5267,Sat3455,$

In [53]:
df.sort_values(by = 'tip' ,ascending= True)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,6392,Fri3780,$
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,6887,Sat4801,$
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,5267,Sat3455,$
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3965,Sat5032,$$
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
...,...,...,...,...,...,...,...,...,...,...,...,...
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,8508,Thur1025,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,9808,Sat239,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$

In [54]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [55]:
df.sort_values(by = 'total_bill',ascending=False,inplace = True)

In [56]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [57]:
df.reset_index(inplace=True,drop=True)

In [58]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [59]:
df.sort_values(['tip', 'total_bill'], ascending=False)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
10,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,9808,Sat239,$$$
2,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
20,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,8508,Thur1025,$$$
...,...,...,...,...,...,...,...,...,...,...,...,...
131,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
195,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3965,Sat5032,$$
240,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,6887,Sat4801,$
242,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,6392,Fri3780,$
243,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,5267,Sat3455,$

In [60]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [61]:
df['price_per_person'].max()

20.27

In [62]:
df['price_per_person'].argmax()

np.int64(8)

In [63]:
df.head(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$
5,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,6604,Sat6240,$$$
6,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,0175,Thur9313,$$$
7,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,6453,Thur3621,$$$
8,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,4029,Sun5140,$$$
9,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,8690,Fri9628,$$$

In [64]:
df['price_per_person'].idxmax()

8

In [65]:
df.corr(numeric_only=True)

                  total_bill       tip      size  price_per_person
total_bill          1.000000  0.675734  0.598315          0.647554
tip                 0.675734  1.000000  0.489299          0.347405
size                0.598315  0.489299  1.000000         -0.175359
price_per_person    0.647554  0.347405 -0.175359          1.000000

In [66]:
df['time'].unique()

array(['Dinner', 'Lunch'], dtype=object)

In [67]:
df['sex'].unique()

array(['Male', 'Female'], dtype=object)

In [68]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [69]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [70]:
df['day'].unique()

array(['Sat', 'Sun', 'Thur', 'Fri'], dtype=object)

In [71]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [72]:
df.day.unique()

array(['Sat', 'Sun', 'Thur', 'Fri'], dtype=object)

In [73]:
df['day'].unique()

array(['Sat', 'Sun', 'Thur', 'Fri'], dtype=object)

In [74]:
df['day'].nunique()

4

In [75]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

# I yol (apply metodu ile)

In [76]:
df['sex'] = df['sex'].apply(lambda x: 'M' if x== 'Male' else 'F')

In [77]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,M,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,M,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,M,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [78]:
df['sex'].nunique()

2

In [79]:
df['sex'].value_counts()

sex
M    157
F     87
Name: count, dtype: int64

# II yol (replace metodu ile)

In [80]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,M,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,M,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,M,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [81]:
df['sex'].replace('Female', 'F', inplace=True)
df['sex'].replace('Male', 'M', inplace=True)

<ipython-input-81-49d2d5d0fd96>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sex'].replace('Female', 'F', inplace=True)
<ipython-input-81-49d2d5d0fd96>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sex'].replace('Male', 'M', inplace=True)

In [82]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,M,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,M,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,M,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [83]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,M,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,M,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,M,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [84]:
df['sex'].replace(['Male', 'Female'], ['M', 'F'], inplace=True)

<ipython-input-84-4fff96c4cfbf>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sex'].replace(['Male', 'Female'], ['M', 'F'], inplace=True)

In [85]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,M,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,M,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,M,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

# III yol map() metodu ilee

In [86]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,M,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,M,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,M,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [87]:
df['sex'].map({'Female' : 'F',
               'Male' : 'M'})

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
239    NaN
240    NaN
241    NaN
242    NaN
243    NaN
Name: sex, Length: 244, dtype: object

In [89]:
simple_df = pd.DataFrame (data = [[1, 2, 2, 2],
                                  [1, 2, 3, 4],
                                  [1, 2, 2, 2],
                                  [1, 2, 2, 2]] ,
                          index = ['a', 'b', 'c', 'd'],
                          columns = ['col1', 'col2', 'col3', 'col4'])

In [90]:
simple_df

   col1  col2  col3  col4
a     1     2     2     2
b     1     2     3     4
c     1     2     2     2
d     1     2     2     2

In [93]:
simple_df.duplicated()

a    False
b    False
c     True
d     True
dtype: bool

In [94]:
simple_df.drop_duplicates() #inplace= True ilə qalıcı hala gətiririk.

   col1  col2  col3  col4
a     1     2     2     2
b     1     2     3     4

In [96]:
simple_df.drop_duplicates(keep= 'first')  # 1 ci təkrarlanan sətiri saxlayır

   col1  col2  col3  col4
a     1     2     2     2
b     1     2     3     4

In [97]:
simple_df.drop_duplicates(keep = 'last') # sonuncu təkrarlanan sətiri saxlayır

   col1  col2  col3  col4
b     1     2     3     4
d     1     2     2     2

In [99]:
simple_df.drop_duplicates(keep = False) # təkrarlanan sətirlərin hamısını silir.

   col1  col2  col3  col4
b     1     2     3     4

In [100]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,M,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,M,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,M,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

# Between() methodu

In [111]:
df[(df['total_bill'] > 10) & (df['total_bill'] < 20)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
97,19.82,3.18,M,No,Sat,Dinner,2,9.91,Christopher Ross,7928,Sat6236,$$
98,19.81,4.19,F,Yes,Thur,Lunch,2,9.90,Kristy Boyd,0068,Thur967,$$
99,19.77,2.00,M,No,Sun,Dinner,4,4.94,James Smith,8229,Sun5814,$$
100,19.65,3.00,F,No,Sat,Dinner,2,9.82,Melinda Murphy,6051,Sat2467,$$
101,19.49,3.51,M,No,Sun,Dinner,2,9.74,Michael Hamilton,1768,Sun1118,$$
...,...,...,...,...,...,...,...,...,...,...,...,...
222,10.29,2.60,F,No,Sun,Dinner,2,5.14,Jessica Ibarra,3713,Sun4474,$$
223,10.27,1.71,M,No,Sun,Dinner,2,5.14,William Riley,1219,Sun2546,$$
224,10.09,2.00,F,Yes,Fri,Lunch,2,5.04,Ruth Weiss,1635,Fri6359,$$
225,10.07,1.25,M,No,Sat,Dinner,2,5.04,Sean Gonzalez,7605,Sat4615,$$
226,10.07,1.83,F,No,Thur,Lunch,1,10.07,Julie Moody,2843,Thur4909,$$

In [105]:
df[df['total_bill'].between(10, 20)] # default olaraq ikisi de daxildir.

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
97,19.82,3.18,M,No,Sat,Dinner,2,9.91,Christopher Ross,7928,Sat6236,$$
98,19.81,4.19,F,Yes,Thur,Lunch,2,9.90,Kristy Boyd,0068,Thur967,$$
99,19.77,2.00,M,No,Sun,Dinner,4,4.94,James Smith,8229,Sun5814,$$
100,19.65,3.00,F,No,Sat,Dinner,2,9.82,Melinda Murphy,6051,Sat2467,$$
101,19.49,3.51,M,No,Sun,Dinner,2,9.74,Michael Hamilton,1768,Sun1118,$$
...,...,...,...,...,...,...,...,...,...,...,...,...
222,10.29,2.60,F,No,Sun,Dinner,2,5.14,Jessica Ibarra,3713,Sun4474,$$
223,10.27,1.71,M,No,Sun,Dinner,2,5.14,William Riley,1219,Sun2546,$$
224,10.09,2.00,F,Yes,Fri,Lunch,2,5.04,Ruth Weiss,1635,Fri6359,$$
225,10.07,1.25,M,No,Sat,Dinner,2,5.04,Sean Gonzalez,7605,Sat4615,$$
226,10.07,1.83,F,No,Thur,Lunch,1,10.07,Julie Moody,2843,Thur4909,$$

In [107]:
df[df['total_bill'].between(10, 20 , inclusive= 'both')] # hər ikisi daxil olmaqla

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
97,19.82,3.18,M,No,Sat,Dinner,2,9.91,Christopher Ross,7928,Sat6236,$$
98,19.81,4.19,F,Yes,Thur,Lunch,2,9.90,Kristy Boyd,0068,Thur967,$$
99,19.77,2.00,M,No,Sun,Dinner,4,4.94,James Smith,8229,Sun5814,$$
100,19.65,3.00,F,No,Sat,Dinner,2,9.82,Melinda Murphy,6051,Sat2467,$$
101,19.49,3.51,M,No,Sun,Dinner,2,9.74,Michael Hamilton,1768,Sun1118,$$
...,...,...,...,...,...,...,...,...,...,...,...,...
222,10.29,2.60,F,No,Sun,Dinner,2,5.14,Jessica Ibarra,3713,Sun4474,$$
223,10.27,1.71,M,No,Sun,Dinner,2,5.14,William Riley,1219,Sun2546,$$
224,10.09,2.00,F,Yes,Fri,Lunch,2,5.04,Ruth Weiss,1635,Fri6359,$$
225,10.07,1.25,M,No,Sat,Dinner,2,5.04,Sean Gonzalez,7605,Sat4615,$$
226,10.07,1.83,F,No,Thur,Lunch,1,10.07,Julie Moody,2843,Thur4909,$$

In [108]:
df[df['total_bill'].between(10, 20, inclusive='neither')] # heç biri daxil deyil

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
97,19.82,3.18,M,No,Sat,Dinner,2,9.91,Christopher Ross,7928,Sat6236,$$
98,19.81,4.19,F,Yes,Thur,Lunch,2,9.90,Kristy Boyd,0068,Thur967,$$
99,19.77,2.00,M,No,Sun,Dinner,4,4.94,James Smith,8229,Sun5814,$$
100,19.65,3.00,F,No,Sat,Dinner,2,9.82,Melinda Murphy,6051,Sat2467,$$
101,19.49,3.51,M,No,Sun,Dinner,2,9.74,Michael Hamilton,1768,Sun1118,$$
...,...,...,...,...,...,...,...,...,...,...,...,...
222,10.29,2.60,F,No,Sun,Dinner,2,5.14,Jessica Ibarra,3713,Sun4474,$$
223,10.27,1.71,M,No,Sun,Dinner,2,5.14,William Riley,1219,Sun2546,$$
224,10.09,2.00,F,Yes,Fri,Lunch,2,5.04,Ruth Weiss,1635,Fri6359,$$
225,10.07,1.25,M,No,Sat,Dinner,2,5.04,Sean Gonzalez,7605,Sat4615,$$
226,10.07,1.83,F,No,Thur,Lunch,1,10.07,Julie Moody,2843,Thur4909,$$

In [109]:
df[df['total_bill'].between(10, 20, inclusive='left')] #yalnız sol sərhəd daxil edilir

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
97,19.82,3.18,M,No,Sat,Dinner,2,9.91,Christopher Ross,7928,Sat6236,$$
98,19.81,4.19,F,Yes,Thur,Lunch,2,9.90,Kristy Boyd,0068,Thur967,$$
99,19.77,2.00,M,No,Sun,Dinner,4,4.94,James Smith,8229,Sun5814,$$
100,19.65,3.00,F,No,Sat,Dinner,2,9.82,Melinda Murphy,6051,Sat2467,$$
101,19.49,3.51,M,No,Sun,Dinner,2,9.74,Michael Hamilton,1768,Sun1118,$$
...,...,...,...,...,...,...,...,...,...,...,...,...
222,10.29,2.60,F,No,Sun,Dinner,2,5.14,Jessica Ibarra,3713,Sun4474,$$
223,10.27,1.71,M,No,Sun,Dinner,2,5.14,William Riley,1219,Sun2546,$$
224,10.09,2.00,F,Yes,Fri,Lunch,2,5.04,Ruth Weiss,1635,Fri6359,$$
225,10.07,1.25,M,No,Sat,Dinner,2,5.04,Sean Gonzalez,7605,Sat4615,$$
226,10.07,1.83,F,No,Thur,Lunch,1,10.07,Julie Moody,2843,Thur4909,$$

In [110]:
df[df['total_bill'].between(10, 20, inclusive='right')] #yalnız sağ sərhəd daxildir.

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
97,19.82,3.18,M,No,Sat,Dinner,2,9.91,Christopher Ross,7928,Sat6236,$$
98,19.81,4.19,F,Yes,Thur,Lunch,2,9.90,Kristy Boyd,0068,Thur967,$$
99,19.77,2.00,M,No,Sun,Dinner,4,4.94,James Smith,8229,Sun5814,$$
100,19.65,3.00,F,No,Sat,Dinner,2,9.82,Melinda Murphy,6051,Sat2467,$$
101,19.49,3.51,M,No,Sun,Dinner,2,9.74,Michael Hamilton,1768,Sun1118,$$
...,...,...,...,...,...,...,...,...,...,...,...,...
222,10.29,2.60,F,No,Sun,Dinner,2,5.14,Jessica Ibarra,3713,Sun4474,$$
223,10.27,1.71,M,No,Sun,Dinner,2,5.14,William Riley,1219,Sun2546,$$
224,10.09,2.00,F,Yes,Fri,Lunch,2,5.04,Ruth Weiss,1635,Fri6359,$$
225,10.07,1.25,M,No,Sat,Dinner,2,5.04,Sean Gonzalez,7605,Sat4615,$$
226,10.07,1.83,F,No,Thur,Lunch,1,10.07,Julie Moody,2843,Thur4909,$$

In [112]:
df[~df['total_bill'].between(10, 20)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,M,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,M,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,M,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$
...,...,...,...,...,...,...,...,...,...,...,...,...
239,7.51,2.00,M,No,Thur,Lunch,2,3.76,Daniel Robbins,1889,Thur6321,$
240,7.25,1.00,F,No,Sat,Dinner,1,7.25,Terri Jones,6887,Sat4801,$
241,7.25,5.15,M,Yes,Sun,Dinner,2,3.62,Larry White,3103,Sun9209,$
242,5.75,1.00,F,Yes,Fri,Dinner,2,2.88,Leah Ramirez,6392,Fri3780,$
243,3.07,1.00,F,Yes,Sat,Dinner,1,3.07,Tiffany Brock,5267,Sat3455,$

In [113]:
df.nlargest(5, 'price_per_person') #price_per_person sütununa görə ən böyük 5 dənə sətiri gətirir.

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
8,40.55,3.00,M,Yes,Sun,Dinner,2,20.27,Stephen Cox,4029,Sun5140,$$$
19,34.63,3.55,M,Yes,Sun,Dinner,2,17.32,Brian Bailey,4848,Sun9851,$$$
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
21,32.90,3.11,M,Yes,Sun,Dinner,2,16.45,Nathan Reynolds,7149,Sun5109,$$$
22,32.83,1.17,M,Yes,Sat,Dinner,2,16.42,Thomas Brown,5508,Sat2929,$$$

In [116]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,M,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,M,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,M,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [118]:
df.sort_values('price_per_person', ascending=True ) # df.sort_index()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
242,5.75,1.00,F,Yes,Fri,Dinner,2,2.88,Leah Ramirez,6392,Fri3780,$
243,3.07,1.00,F,Yes,Sat,Dinner,1,3.07,Tiffany Brock,5267,Sat3455,$
220,10.33,1.67,F,No,Sun,Dinner,3,3.44,Elizabeth Foster,6033,Sun9715,$$
219,10.34,1.66,M,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
241,7.25,5.15,M,Yes,Sun,Dinner,2,3.62,Larry White,3103,Sun9209,$
...,...,...,...,...,...,...,...,...,...,...,...,...
22,32.83,1.17,M,Yes,Sat,Dinner,2,16.42,Thomas Brown,5508,Sat2929,$$$
21,32.90,3.11,M,Yes,Sun,Dinner,2,16.45,Nathan Reynolds,7149,Sun5109,$$$
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
19,34.63,3.55,M,Yes,Sun,Dinner,2,17.32,Brian Bailey,4848,Sun9851,$$$
8,40.55,3.00,M,Yes,Sun,Dinner,2,20.27,Stephen Cox,4029,Sun5140,$$$

In [120]:
df.sort_values('price_per_person', ascending= False).head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
8,40.55,3.00,M,Yes,Sun,Dinner,2,20.27,Stephen Cox,4029,Sun5140,$$$
19,34.63,3.55,M,Yes,Sun,Dinner,2,17.32,Brian Bailey,4848,Sun9851,$$$
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
21,32.90,3.11,M,Yes,Sun,Dinner,2,16.45,Nathan Reynolds,7149,Sun5109,$$$
22,32.83,1.17,M,Yes,Sat,Dinner,2,16.42,Thomas Brown,5508,Sat2929,$$$

In [121]:
df.nlargest(6, 'tip')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
10,39.42,7.58,M,No,Sat,Dinner,4,9.86,Lance Peterson,9808,Sat239,$$$
2,48.27,6.73,M,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
20,34.30,6.70,M,No,Thur,Lunch,6,5.72,Steven Carlson,8508,Thur1025,$$$
39,28.17,6.50,F,Yes,Sat,Dinner,3,9.39,Marissa Jackson,1962,Sat3374,$$

In [122]:
df.nsmallest(3, 'tip')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
195,12.60,1.0,M,Yes,Sat,Dinner,2,6.30,Matthew Myers,3965,Sat5032,$$
240,7.25,1.0,F,No,Sat,Dinner,1,7.25,Terri Jones,6887,Sat4801,$
242,5.75,1.0,F,Yes,Fri,Dinner,2,2.88,Leah Ramirez,6392,Fri3780,$

In [125]:
df.nsmallest(columns =['total_bill', 'tip'], n = 3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
243,3.07,1.0,F,Yes,Sat,Dinner,1,3.07,Tiffany Brock,5267,Sat3455,$
242,5.75,1.0,F,Yes,Fri,Dinner,2,2.88,Leah Ramirez,6392,Fri3780,$
240,7.25,1.0,F,No,Sat,Dinner,1,7.25,Terri Jones,6887,Sat4801,$

In [126]:
df.sample(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
205,11.69,2.31,M,No,Thur,Lunch,2,5.84,Kenneth Goodman,1010,Thur8289,$$
29,30.40,5.60,M,No,Sun,Dinner,4,7.60,Todd Cooper,1263,Sun2274,$$$
153,15.77,2.23,F,No,Sat,Dinner,2,7.88,Ashley Shelton,3213,Sat9786,$$
137,16.49,2.00,M,No,Sun,Dinner,4,4.12,Christopher Soto,1434,Sun1781,$$
123,17.59,2.64,M,No,Sat,Dinner,3,5.86,Michael Johnson,8108,Sat1667,$$
192,12.74,2.01,F,Yes,Thur,Lunch,2,6.37,Abigail Parks,0590,Thur2544,$$
243,3.07,1.00,F,Yes,Sat,Dinner,1,3.07,Tiffany Brock,5267,Sat3455,$
71,22.75,3.25,F,No,Fri,Dinner,2,11.38,Jamie Garza,2068,Fri2318,$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
131,16.99,1.01,F,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$

In [ ]:
#Done