In [5]:
!wget https://raw.githubusercontent.com/EmKa-Academy/Udemy-Python_Numpy_Pandas/refs/heads/main/Pandas/Data/mpg.csv

--2025-03-29 12:26:53--  https://raw.githubusercontent.com/EmKa-Academy/Udemy-Python_Numpy_Pandas/refs/heads/main/Pandas/Data/mpg.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17727 (17K) [text/plain]
Saving to: ‘mpg.csv.1’

mpg.csv.1           100%[===================>]  17.31K  --.-KB/s    in 0s

2025-03-29 12:26:53 (33.8 MB/s) - ‘mpg.csv.1’ saved [17727/17727]

In [6]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/mpg.csv')

In [8]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [9]:
df.shape

(398, 9)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [12]:
df['horsepower'].astype(np.int64)

ValueError: invalid literal for int() with base 10: '?'

In [13]:
df[df['horsepower'] == '?']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,?,2046,19.0,71,1,ford pinto
126,21.0,6,200.0,?,2875,17.0,74,1,ford maverick
330,40.9,4,85.0,?,1835,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,?,2905,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,?,2320,15.8,81,2,renault 18i
374,23.0,4,151.0,?,3035,20.5,82,1,amc concord dl

In [15]:
df['horsepower'].replace('?' , np.nan, inplace= True)

In [20]:
df['horsepower'] = df['horsepower'].astype(np.float64)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(4), int64(4), object(1)
memory usage: 28.1+ KB

In [22]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino

In [24]:
df['model_year'].unique()

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])

In [26]:
df['model_year'].value_counts() #unique dəyərlərinn sayı

model_year
73    40
78    36
76    34
82    31
75    30
80    29
79    29
81    29
70    29
71    28
72    28
77    28
74    27
Name: count, dtype: int64

# .groupby() metodu

In [ ]:
# .groupby(sutun_adi) daha sonra aggregate functions
# mean(),
# sum(),
# max, min(),
# std(),
# var(),
# size(),
# count(),
# nth(),
# describe(),
# first, last()
# sem()

In [27]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000

In [28]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino

In [32]:
df.groupby('model_year')['mpg'].mean()

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64

In [35]:
df.groupby(by= ['model_year', 'cylinders']).mean(numeric_only= True)

                            mpg  displacement  horsepower       weight  \
model_year cylinders
70         4          25.285714    107.000000   87.714286  2292.571429
           6          20.500000    199.000000   91.750000  2710.500000
           8          14.111111    367.555556  183.666667  3940.055556
71         4          27.461538    101.846154   77.583333  2056.384615
           6          18.000000    243.375000   98.875000  3171.875000
           8          13.428571    371.714286  166.857143  4537.714286
72         3          19.000000     70.000000   97.000000  2330.000000
           4          23.428571    111.535714   85.142857  2382.642857
           8          13.615385    344.846154  159.692308  4228.384615
73         3          18.000000     70.000000   90.000000  2124.000000
           4          22.727273    109.272727   82.909091  2338.090909
           6          19.000000    212.250000  102.125000  2917.125000
           8          13.200000    365.250000  170.000000  4279.050000
74         4          27.800000     96.533333   74.000000  2151.466667
           6          17.857143    230.428571  101.666667  3320.000000
           8          14.200000    315.200000  146.000000  4438.400000
75         4          25.250000    114.833333   84.916667  2489.250000
           6          17.583333    233.750000   96.750000  3398.333333
           8          15.666667    330.500000  142.000000  4108.833333
76         4          26.766667    106.333333   75.600000  2306.600000
           6          20.000000    221.400000   98.700000  3349.600000
           8          14.666667    324.000000  146.333333  4064.666667
77         3          21.500000     80.000000  110.000000  2720.000000
           4          29.107143    106.500000   78.785714  2205.071429
           6          19.500000    220.400000  102.000000  3383.000000
           8          16.000000    335.750000  152.375000  4177.500000
78         4          29.576471    112.117647   79.705882  2296.764706
           5          20.300000    131.000000  103.000000  2830.000000
           6          19.066667    213.250000  109.833333  3314.166667
           8          19.050000    300.833333  135.500000  3563.333333
79         4          31.525000    113.583333   75.750000  2357.583333
           5          25.400000    183.000000   77.000000  3530.000000
           6          22.950000    205.666667  105.000000  3025.833333
           8          18.630000    321.400000  131.900000  3862.900000
80         3          23.700000     70.000000  100.000000  2420.000000
           4          34.612000    111.000000   74.043478  2360.080000
           5          36.400000    121.000000   67.000000  2950.000000
           6          25.900000    196.500000  111.000000  3145.500000
81         4          32.814286    108.857143   72.950000  2275.476190
           6          23.428571    184.000000  100.714286  3093.571429
           8          26.600000    350.000000  105.000000  3725.000000
82         4          32.071429    118.571429   79.148148  2402.321429
           6          28.333333    225.000000  102.333333  2931.666667

                      acceleration    origin
model_year cylinders
70         4             16.000000  2.285714
           6             15.500000  1.000000
           8             11.194444  1.000000
71         4             16.961538  1.923077
           6             14.750000  1.000000
           8             12.214286  1.000000
72         3             13.500000  3.000000
           4             17.214286  1.928571
           8             13.000000  1.000000
73         3             13.500000  3.000000
           4             17.136364  2.000000
           6             15.687500  1.250000
           8             12.250000  1.000000
74         4             16.400000  2.200000
           6             16.857143  1.000000
           8             14.700000  1.000000
75         4             15.833333  2.166667
           6             17.708333  1.000000
           8             13.166667  1.000000
76         4             16.866667  1.866667
           6             17.000000  1.300000
           8             13.222222  1.000000
77         3             13.500000  3.000000
           4             16.064286  1.857143
           6             16.900000  1.400000
           8             13.662500  1.000000
78         4             16.282353  2.117647
           5             15.900000  2.000000
           6             16.391667  1.166667
           8             13.266667  1.000000
79         4             15.991667  1.583333
           5             20.100000  2.000000
           6             15.433333  1.000000
           8             15.400000  1.000000
80         3             12.500000  3.000000
           4             17.144000  2.200000
           5             19.900000  2.000000
           6             15.050000  2.000000
81         4             16.466667  2.095238
           6             15.442857  1.714286
           8             19.000000  1.000000
82         4             16.703571  1.714286
           6             16.033333  1.000000

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(4), int64(4), object(1)
memory usage: 28.1+ KB

In [36]:
print('hello')

hello

In [37]:
%timeit
print('hello')

hello

In [38]:
#Done