In [119]:
import numpy as np
import pandas as pd

In [120]:
!wget https://raw.githubusercontent.com/EmKa-Academy/Canli-Ders-Notebooklari/refs/heads/main/Batch-1/Pandas-Dersleri/DATA/tips.csv

--2025-03-14 10:44:39--  https://raw.githubusercontent.com/EmKa-Academy/Canli-Ders-Notebooklari/refs/heads/main/Batch-1/Pandas-Dersleri/DATA/tips.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18505 (18K) [text/plain]
Saving to: ‘tips.csv.2’

tips.csv.2          100%[===================>]  18.07K  --.-KB/s    in 0.001s

2025-03-14 10:44:39 (25.2 MB/s) - ‘tips.csv.2’ saved [18505/18505]

In [223]:
df = pd.read_csv('/content/tips.csv')
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [122]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

# Built-in funksiyalar və metodlar

# .apply()

# I yol

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [124]:
def son4(number):
    return str(number)[-4:]

In [125]:
df['CC Number'].apply(son4)

0      3410
1      9230
2      1322
3      5994
4      7221
       ...
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: object

In [126]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [127]:
df['CC Number'] = df['CC Number'].apply(son4)

In [128]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

# II yol

In [129]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    object
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(1), object(7)
memory usage: 21.1+ KB

In [131]:
df['CC Number'] = df['CC Number'].apply(lambda x: str(x)[-4:])

In [132]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

# III yol

In [133]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [134]:
df['CC Number'].astype(str).str[-4:]

0      3410
1      9230
2      1322
3      5994
4      7221
       ...
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: object

In [135]:
df['CC Number'] = df['CC Number'].astype(str).str[-4:]

In [136]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [137]:
# Əgər ödənən hesab 10 -dan azdırsa $ simvolu, 10 və 30 arasındadırsa $$, 30 dan çoxdursa $$$ simvolu yeni sütunda uyğun olaraq yazılsın

# I yol

In [138]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [139]:
def fiyat_kateqori(x):
    if x < 10 :
        return '$'
    elif 10 <= x < 30 :
        return '$$'
    else :
        return '$$$'

In [140]:
df['total_bill'].apply(fiyat_kateqori)

0      $$
1      $$
2      $$
3      $$
4      $$
       ..
239    $$
240    $$
241    $$
242    $$
243    $$
Name: total_bill, Length: 244, dtype: object

In [141]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [142]:
df['price_category'] = df['total_bill'].apply(fiyat_kateqori)

In [143]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

# II yol lambda expression

In [144]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [145]:
df['price_category'] = df['total_bill'].apply(lambda x : '$' if x < 10 else '$$' if 10 <= x < 30 else '$$$')

In [146]:
df.sample(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
226,10.09,2.00,Female,Yes,Fri,Lunch,2,5.04,Ruth Weiss,1635,Fri6359,$$
205,16.47,3.23,Female,Yes,Thur,Lunch,3,5.49,Carly Reyes,6486,Thur8084,$$
32,15.06,3.00,Female,No,Sat,Dinner,2,7.53,Amanda Wilson,1560,Sat1327,$$
219,30.14,3.09,Female,Yes,Sat,Dinner,4,7.54,Shelby House,3252,Sat8863,$$$
152,17.26,2.74,Male,No,Sun,Dinner,3,5.75,Gregory Smith,3741,Sun5205,$$
134,18.26,3.25,Female,No,Thur,Lunch,2,9.13,Karen Rodriguez,8911,Thur75,$$
233,10.77,1.47,Male,No,Sat,Dinner,2,5.38,Paul Novak,0858,Sat1467,$$
181,23.33,5.65,Male,Yes,Sun,Dinner,2,11.66,Jason Cox,6223,Sun3402,$$
21,20.29,2.75,Female,No,Sat,Dinner,2,10.14,Natalie Gardner,9749,Sat9618,$$
135,8.51,1.25,Female,No,Thur,Lunch,2,4.26,Rebecca Harris,6174,Thur6600,$

# III yol vectorized (ən sürətlisi)

In [147]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [148]:
df.drop('price_category', axis = 1, inplace=True )

In [149]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

In [150]:
np.full((2,3), 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [151]:
def fiyat_kateqori_vectorized(bill):
    categories = np.full_like(bill, '$', dtype= 'U3')
    categories[(bill >= 10) & (bill < 30)] = '$$'
    categories[bill >= 30] = '$$$'
    return categories

In [152]:
df['total_bill'].keys()

RangeIndex(start=0, stop=244, step=1)

In [153]:
df['total_bill'].values

array([16.99, 10.34, 21.01, 23.68, 24.59, 25.29,  8.77, 26.88, 15.04,
       14.78, 10.27, 35.26, 15.42, 18.43, 14.83, 21.58, 10.33, 16.29,
       16.97, 20.65, 17.92, 20.29, 15.77, 39.42, 19.82, 17.81, 13.37,
       12.69, 21.7 , 19.65,  9.55, 18.35, 15.06, 20.69, 17.78, 24.06,
       16.31, 16.93, 18.69, 31.27, 16.04, 17.46, 13.94,  9.68, 30.4 ,
       18.29, 22.23, 32.4 , 28.55, 18.04, 12.54, 10.29, 34.81,  9.94,
       25.56, 19.49, 38.01, 26.41, 11.24, 48.27, 20.29, 13.81, 11.02,
       18.29, 17.59, 20.08, 16.45,  3.07, 20.23, 15.01, 12.02, 17.07,
       26.86, 25.28, 14.73, 10.51, 17.92, 27.2 , 22.76, 17.29, 19.44,
       16.66, 10.07, 32.68, 15.98, 34.83, 13.03, 18.28, 24.71, 21.16,
       28.97, 22.49,  5.75, 16.32, 22.75, 40.17, 27.28, 12.03, 21.01,
       12.46, 11.35, 15.38, 44.3 , 22.42, 20.92, 15.36, 20.49, 25.21,
       18.24, 14.31, 14.  ,  7.25, 38.07, 23.95, 25.71, 17.31, 29.93,
       10.65, 12.43, 24.08, 11.69, 13.42, 14.26, 15.95, 12.48, 29.8 ,
        8.52, 14.52, 11.38, 22.82, 19.08, 20.27, 11.17, 12.26, 18.26,
        8.51, 10.33, 14.15, 16.  , 13.16, 17.47, 34.3 , 41.19, 27.05,
       16.43,  8.35, 18.64, 11.87,  9.78,  7.51, 14.07, 13.13, 17.26,
       24.55, 19.77, 29.85, 48.17, 25.  , 13.39, 16.49, 21.5 , 12.66,
       16.21, 13.81, 17.51, 24.52, 20.76, 31.71, 10.59, 10.63, 50.81,
       15.81,  7.25, 31.85, 16.82, 32.9 , 17.89, 14.48,  9.6 , 34.63,
       34.65, 23.33, 45.35, 23.17, 40.55, 20.69, 20.9 , 30.46, 18.15,
       23.1 , 15.69, 19.81, 28.44, 15.48, 16.58,  7.56, 10.34, 43.11,
       13.  , 13.51, 18.71, 12.74, 13.  , 16.4 , 20.53, 16.47, 26.59,
       38.73, 24.27, 12.76, 30.06, 25.89, 48.33, 13.27, 28.17, 12.9 ,
       28.15, 11.59,  7.74, 30.14, 12.16, 13.42,  8.58, 15.98, 13.42,
       16.27, 10.09, 20.45, 13.28, 22.12, 24.01, 15.69, 11.61, 10.77,
       15.53, 10.07, 12.6 , 32.83, 35.83, 29.03, 27.18, 22.67, 17.82,
       18.78])

In [154]:
df['price_category'] = fiyat_kateqori_vectorized(df['total_bill'].values)

In [155]:
df.sample(7)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
64,17.59,2.64,Male,No,Sat,Dinner,3,5.86,Michael Johnson,8108,Sat1667,$$
114,25.71,4.00,Female,No,Sun,Dinner,3,8.57,Katie Smith,1292,Sun6492,$$
148,9.78,1.73,Male,No,Thur,Lunch,2,4.89,David Stewart,6399,Thur7276,$
120,11.69,2.31,Male,No,Thur,Lunch,2,5.84,Kenneth Goodman,1010,Thur8289,$$
71,17.07,3.00,Female,No,Sat,Dinner,3,5.69,Teresa Fisher,6367,Sat3469,$$
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,4029,Sun5140,$$$
86,13.03,2.00,Male,No,Thur,Lunch,2,6.52,Derek Thomas,7557,Thur6793,$$

# .apply() metodunu birdən çox sütuna tətbiq etmək

# I yol

In [156]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [157]:
def square(x):
    return x**2

In [158]:
# df[['total_bill', 'tip']] = df[['total_bill', 'tip']].apply(square)
df[['total_bill', 'tip']].apply(square)

     total_bill      tip
0      288.6601   1.0201
1      106.9156   2.7556
2      441.4201  12.2500
3      560.7424  10.9561
4      604.6681  13.0321
..          ...      ...
239    842.7409  35.0464
240    738.7524   4.0000
241    513.9289   4.0000
242    317.5524   3.0625
243    352.6884   9.0000

[244 rows x 2 columns]

# II yol

In [159]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [160]:
df[['total_bill', 'tip']].apply(lambda x : x**2 )
# df[['total_bill', 'tip']] = df[['total_bill', 'tip']].apply(lambda x: x**2)

     total_bill      tip
0      288.6601   1.0201
1      106.9156   2.7556
2      441.4201  12.2500
3      560.7424  10.9561
4      604.6681  13.0321
..          ...      ...
239    842.7409  35.0464
240    738.7524   4.0000
241    513.9289   4.0000
242    317.5524   3.0625
243    352.6884   9.0000

[244 rows x 2 columns]

# III yol vectorized(ən sürətlisi)

In [161]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [162]:
# df['total_bill'] = np.square(df['total_bill'])
np.square(df['total_bill'])

0      288.6601
1      106.9156
2      441.4201
3      560.7424
4      604.6681
         ...
239    842.7409
240    738.7524
241    513.9289
242    317.5524
243    352.6884
Name: total_bill, Length: 244, dtype: float64

In [163]:
# df[['total_bill', 'tip']] = np.square(df[['total_bill', 'tip']])
np.square(df[['total_bill', 'tip']])

     total_bill      tip
0      288.6601   1.0201
1      106.9156   2.7556
2      441.4201  12.2500
3      560.7424  10.9561
4      604.6681  13.0321
..          ...      ...
239    842.7409  35.0464
240    738.7524   4.0000
241    513.9289   4.0000
242    317.5524   3.0625
243    352.6884   9.0000

[244 rows x 2 columns]

In [164]:
df.describe()

       total_bill         tip        size  price_per_person
count  244.000000  244.000000  244.000000        244.000000
mean    19.785943    2.998279    2.569672          7.888197
std      8.902412    1.383638    0.951100          2.914234
min      3.070000    1.000000    1.000000          2.880000
25%     13.347500    2.000000    2.000000          5.800000
50%     17.795000    2.900000    2.000000          7.255000
75%     24.127500    3.562500    3.000000          9.390000
max     50.810000   10.000000    6.000000         20.270000

In [165]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [166]:
df.sort_values(by = 'total_bill', ascending= True) #default halda ascending True olduğu üçün artan sıra ilə sıralayır

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,5267,Sat3455,$
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,6392,Fri3780,$
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,6887,Sat4801,$
172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,Larry White,3103,Sun9209,$
149,7.51,2.00,Male,No,Thur,Lunch,2,3.76,Daniel Robbins,1889,Thur6321,$
...,...,...,...,...,...,...,...,...,...,...,...,...
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$

In [167]:
df.sort_values(by = 'total_bill', ascending= False) # azalan sira ile

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$
...,...,...,...,...,...,...,...,...,...,...,...,...
149,7.51,2.00,Male,No,Thur,Lunch,2,3.76,Daniel Robbins,1889,Thur6321,$
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,6887,Sat4801,$
172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,Larry White,3103,Sun9209,$
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,6392,Fri3780,$
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,5267,Sat3455,$

In [168]:
df.sort_values(by = 'tip' ,ascending= True)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,5267,Sat3455,$
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3965,Sat5032,$$
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,6392,Fri3780,$
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,6887,Sat4801,$
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
...,...,...,...,...,...,...,...,...,...,...,...,...
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,8508,Thur1025,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,9808,Sat239,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$

In [169]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251,$$

In [170]:
df.sort_values(by = 'total_bill',ascending=False,inplace = True)

In [171]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [174]:
df.reset_index(inplace=True,drop=True)

In [175]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [176]:
df.sort_values(['tip', 'total_bill'], ascending=False)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
10,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,9808,Sat239,$$$
2,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
20,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,8508,Thur1025,$$$
...,...,...,...,...,...,...,...,...,...,...,...,...
131,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959,$$
195,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3965,Sat5032,$$
240,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,6887,Sat4801,$
242,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,6392,Fri3780,$
243,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,5267,Sat3455,$

In [178]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [179]:
df['price_per_person'].max()

20.27

In [180]:
df['price_per_person'].argmax()

8

In [181]:
df.head(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$
5,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,6604,Sat6240,$$$
6,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,0175,Thur9313,$$$
7,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,6453,Thur3621,$$$
8,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,4029,Sun5140,$$$
9,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,8690,Fri9628,$$$

In [182]:
df['price_per_person'].idxmax()

8

In [186]:
df.corr(numeric_only=True)

                  total_bill       tip      size  price_per_person
total_bill          1.000000  0.675734  0.598315          0.647554
tip                 0.675734  1.000000  0.489299          0.347405
size                0.598315  0.489299  1.000000         -0.175359
price_per_person    0.647554  0.347405 -0.175359          1.000000

In [189]:
df['time'].unique()

array(['Dinner', 'Lunch'], dtype=object)

In [188]:
df['sex'].unique()

array(['Male', 'Female'], dtype=object)

In [191]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [193]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [194]:
df['day'].unique()

array(['Sat', 'Sun', 'Thur', 'Fri'], dtype=object)

In [195]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [196]:
df.day.unique()

array(['Sat', 'Sun', 'Thur', 'Fri'], dtype=object)

In [197]:
df['day'].unique()

array(['Sat', 'Sun', 'Thur', 'Fri'], dtype=object)

In [198]:
df['day'].nunique()

4

In [200]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

# I yol (apply metodu ile)

In [203]:
df['sex'] = df['sex'].apply(lambda x: 'M' if x== 'Male' else 'F')

In [204]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_category
0,50.81,10.00,M,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,M,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,48.27,6.73,M,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
3,48.17,5.00,M,No,Sun,Dinner,6,8.03,Ryan Gonzales,3321,Sun7518,$$$
4,45.35,3.50,M,Yes,Sun,Dinner,3,15.12,Jose Parsons,9910,Sun2337,$$$

In [206]:
df['sex'].nunique()

2

In [207]:
df['sex'].value_counts()

sex
M    157
F     87
Name: count, dtype: int64

# II yol (replace metodu ile)

In [209]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [215]:
df['sex'].replace('Female', 'F', inplace=True)
df['sex'].replace('Male', 'M', inplace=True)

In [216]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,F,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,M,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,M,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,M,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,F,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [218]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [221]:
df['sex'].replace(['Male', 'Female'], ['M', 'F'], inplace=True)

<ipython-input-221-4fff96c4cfbf>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sex'].replace(['Male', 'Female'], ['M', 'F'], inplace=True)

In [222]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,F,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,M,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,M,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,M,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,F,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

# III yol map() metodu ilee

In [224]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [225]:
df['sex'].map({'Female' : 'F',
               'Male' : 'M'})

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

In [ ]:
#Done.